name: "📦  Suggest a project"
description: "Do you like to suggest a project that hasn't been added to this best-of list yet?"
title: "Add project: "
labels: ["add-project"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure that the project was not already added or suggested to this best-of list.

        (Existing projects are recorded in [projects.yaml](https://github.com/YDX-2147483647/best-of-typst/blob/main/projects.yaml) or [README.md](https://github.com/YDX-2147483647/best-of-typst/blob/main/README.md), and others’ requests are in [Issues](https://github.com/YDX-2147483647/best-of-typst/issues?q=is%3Aopen+label%3Aadd-project))

  - type: markdown
    attributes:
      value: |
        ### Project details

        Please fill out as much of the following information as possible.
        It will assist human review and also help the robot draft a pull request.

  - type: input
    id: name
    attributes:
      label: Name
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL
      description: GitHub, GitLab, Gitee, Greasy Fork…

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Choose one of the existing categories from the README.md or projects.yaml file
      options:
        # sync-categories: start
        - 📚 Documentation
        - 📝 Writing
        - 📐 Math
        - 🧾 Bibliography
        - ⚔️ Mix writing
        - 🎩 Conversion
        - 🚀 Package development
        - 🏗 Documentation infrastructure
        - 💻 Programming
        - 🐱‍🐉 Miscellaneous
        # sync-categories: end

  - type: checkboxes
    id: labels
    attributes:
      label: Labels
      description: Select one or more labels.
      options:
        # sync-labels: start
        - label: 🤖 CLI — Command-line programs with pre-built binaries available.
        - label: 🥡 Runnable — Runnable projects that need a proper environment (e.g., pip/npm/cargo install).
        - label: 🔌 API — Libraries providing API for development.
        - label: 🎨 App — Local apps with graphical interfaces, typically provided as installers or portable versions.
        - label: 🦋 Web — Web pages and Web apps.
        - label: 🧩 Extension — Browser addons and user scripts, and other kinds of extensions.
        - label: 🌌 Typst package — Projects that are also available as Typst packages, and experimental unpublished local packages.
        - label: 🗺️ Multilingual — Projects that are available in multiple languages or scripts.
        - label: 🐧 non-English — Projects that are not available in English.
        # sync-labels: end

  - type: textarea
    attributes:
      label: Package registries
      description: Links to the project in package registries or catalogs (if any).
      placeholder: |
        Examples:
        https://pypi.org/project/showman/
        https://www.npmjs.com/package/astro-typst
        https://crates.io/crates/typstyle or https://lib.rs/crates/tinymist
        https://pkg.go.dev/github.com/francescoalemanno/gotypst

  - type: markdown
    attributes:
      value: |
        ### Additional context

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or additional information about the project.
      placeholder: (Optional)
